from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor

# PRESENTATION
SLIDE_WIDTH = Inches(13.333)
SLIDE_HEIGHT = Inches(7.5)

DEFAULT_LAYOUT_INDEX = 6

# MARGINS
LEFT_MARGIN = Inches(0.5)
RIGHT_MARGIN = Inches(0.5)
TOP_MARGIN = Inches(0.4)
BOTTOM_MARGIN = Inches(0.4)

# DEFAULT FONT
FONT_FAMILY = "Calibri"

TITLE_FONT_SIZE = Pt(24)
HEADING_FONT_SIZE = Pt(20)
SUBHEADING_FONT_SIZE = Pt(18)
BODY_FONT_SIZE = Pt(16)
SMALL_FONT_SIZE = Pt(13)

# COLORS
BLACK = RGBColor(0, 0, 0)
WHITE = RGBColor(255, 255, 255)

TITLE_COLOR = RGBColor(33, 33, 33)
TEXT_COLOR = RGBColor(40, 40, 40)
SUBTEXT_COLOR = RGBColor(90, 90, 90)

PRIMARY_COLOR = RGBColor(33, 150, 243)
SECONDARY_COLOR = RGBColor(76, 175, 80)
ACCENT_COLOR = RGBColor(255, 152, 0)

SUCCESS_COLOR = RGBColor(46, 125, 50)
WARNING_COLOR = RGBColor(255, 193, 7)
ERROR_COLOR = RGBColor(211, 47, 47)

# IMAGE SETTINGS
IMAGE_DPI = 300

# GRAPH SETTINGS
GRAPH_WIDTH = Inches(11.3)
GRAPH_HEIGHT = Inches(6.2)

# DIAGRAM SETTINGS
DIAGRAM_WIDTH = Inches(11.3)
DIAGRAM_HEIGHT = Inches(6.2)

# TEXTBOX DEFAULTS
TEXTBOX_WIDTH = Inches(12)
TEXTBOX_HEIGHT = Inches(6)

# BACKGROUND
DEFAULT_BACKGROUND = "assets/backgrounds/slide.png"